### ISSUE TITLE
Add Reddit scraping

### ISSUE THREAD

**Issue by ghost** [sam5epi0l/BotTuber#5]
**Is your feature request related to a problem? Please describe.**
Add Reddit scraping

**Describe the solution you'd like**
An option to choose between Instagram and Reddit for data scraping.

**Describe alternatives you've considered**
Reddit Scraping can be done with [bulk-downloader-for-reddit](https://github.com/aliparlakci/bulk-downloader-for-reddit) library. The good thing is, it doesn't require any API authentication.

**Comment by sam5epi0l** [comment]
> **Is your feature request related to a problem? Please describe.** Add Reddit scraping
> 
> **Describe the solution you'd like** An option to choose between Instagram and Reddit for data scraping.
> 
> **Describe alternatives you've considered** Reddit Scraping can be done with [bulk-downloader-for-reddit](https://github.com/aliparlakci/bulk-downloader-for-reddit) library. The good thing is, it doesn't require any API authentication.

Spoiler alert: This feature will be in a new repository.
Thanks for your suggestions!

**Comment by nessquin** [comment]
And upload thumbnail, pls :)

**Comment by sam5epi0l** [comment]
> And upload thumbnail, pls :)

ok.. but how do you want thumbnail to be generated??

**Comment by nessquin** [comment]
Random frames from the video are cropped and inserted by 3(?), possibly with text. Sorry, English is not my native language
In fact, I'm more interested in the technical side of uploading to YouTube

**Comment by ghost** [comment]
> > **Is your feature request related to a problem? Please describe.** Add Reddit scraping
> > **Describe the solution you'd like** An option to choose between Instagram and Reddit for data scraping.
> > **Describe alternatives you've considered** Reddit Scraping can be done with [bulk-downloader-for-reddit](https://github.com/aliparlakci/bulk-downloader-for-reddit) library. The good thing is, it doesn't require any API authentication.
> 
> Spoiler alert: This feature will be in a new repository. Thanks for your suggestions!

Any Updates?
