### ISSUE TITLE
Module Not Found

### ISSUE THREAD

**Issue by Chandima1990** [sam5epi0l/BotTuber#6]
When I try these steps and finally run python3 botTuber.py this error was thrown. But then when I tried to re-install the missing module it is already installed.
![image](https://user-images.githubusercontent.com/15955557/154488066-8f7fcac8-2db8-422a-bd6a-96fa6a4e7edd.png)

I tried uninstalling the module and reinstall it, but same.
How can I resolve this? Not quite sure whether it is a bug or not. Can someone help me out?

**Comment by sam5epi0l** [comment]
It's not a bug in BotTuber
cd to BotTuber Folder, and run
`pip3 install -r requirements.txt`
If that's not helping than try it in any Linux distro

**Comment by sam5epi0l** [comment]
It's not a bug in BotTuber
cd to BotTuber Folder, and run
`pip3 install -r requirements.txt`
If that's not helping than try it in any Linux distro

**Comment by Chandima1990** [comment]
Tried both and still the same.
![image](https://user-images.githubusercontent.com/15955557/154537048-27a00cf8-9b01-45d6-82af-05360cd5ccbf.png)

**Comment by sam5epi0l** [comment]
Try to update things
```
apt update && apt upgrade -y
apt install python3 python3-pip
pip3 install -r requirements.txt
```

**Comment by Chandima1990** [comment]
Actually, I was trying this in a WSL on Windows. Once moved to ubuntu and tried it worked. Thanks.
